 let fixedMarkers = [
  ["Varázslatos lovak Vetle","1.jpg"],
  ["Varázslatos lovak Lebkuchen","2.jpg"],
  ["Holland Melegvérű","3.jpg"],
  ["Varázslatos lovak Audra","4.jpg"],
  ["Varázslatos lovak Alvirah","5.jpg"],
  ["Belga melegvérű","6.jpg"],
  ["Welsh póni","7.jpg"],
  ["Appaloosa","8.jpg"],
  ["Amerikai foltos ló","9.jpg"],
  ["Dartmoor póni","10.jpg"],
  ["Morgan","11.jpg"],
  ["Musztáng","12.jpg"],
  ["Varázslatos lovak Prisma","13.jpg"],
  ["Varázslatos lovak Tenebri","14.jpg"],
  ["Pinto arab","15.jpg"],
  ["Lipicai","16.jpg"],
  ["Varázslatos lovak Ephyra","17.jpg"],
  ["Varázslatos lovak Calder","18.jpg"],
  ["Finn ló","19.jpg"],
  ["Tennessee walking ló","20.jpg"],
  ["Varázslatos lovak Kátur","21.jpg"],
  ["Varázslatos lovak Sylvan, az unikornis","22.jpg"],
  ["Varázslatos lovak Laverna","23.jpg"],
  ["Varázslatos lovak Nemain","24.jpg"],
  ["Galaxy","25.jpg"],
  ["Varázslatos lovak Hemera","26.jpg"],
  ["Varázslatos lovak Antheia","27.jpg"],
  ["A Connemara","28.jpg"],
  ["Shire","29.jpg"],
  ["Varázslatos lovak Proteus","30.jpg"],
  ["Varázslatos lovak Sedna","31.jpg"],
  ["Haflingi","32.jpg"],
  ["Paso fino","33.jpg"],
  ["Angol Telivér","34.jpg"],
  ["Varázslatos lovak Birkir","35.jpg"],
  ["Varázslatos lovak Hanami","36.jpg"],
  ["Varázslatos lovak Árnyvért","37.jpg"],
  ["Varázslatos lovak Hótáncos","38.jpg"],
  ["Izlandi póni","39.jpg"],
  ["Amerikai foltos ló","40.jpg"],
  ["Varázslatos lovak Sirató","41.jpg"],
  ["Varázslatos lovak Alkonyrém","42.jpg"],
  ["Knabstrupper","43.jpg"],
  ["Lélekparipa","44.jpg"],
  ["Varázslatos lovak Aldrach","45.jpg"],
  ["Varázslatos lovak Faramawr","46.jpg"],
  ["Percheron","47.jpg"],
  ["Arab telivér","48.jpg"],
  ["Varázslatos lovak Petra","49.jpg"],
  ["Varázslatos lovak Erinys","50.jpg"],
  ["Gotland póni","51.jpg"],
  ["Jorviki fríz","52.jpg"],
  ["Varázslatos lovak Heidrun","53.jpg"],
  ["Jorviki ősló Zsarátsörény","54.jpg"],
  ["Jorviki ősló","55.jpg"],
  ["Varázslatos lovak Tombhoof","56.jpg"],
  ["Göndör szőrű ló (curly)","57.jpg"],
  ["Varázslatos lovak Dorcha","58.jpg"],
  ["Varázslatos lovak Solas","59.jpg"],
 ["Marwari","60.jpg"],
 ["Északsvéd rúnavágtázó","61.jpg"],
 ["Varázslatos lovak Kampos","62.jpg"],
 ["Varázslatos lovak Tellina","63.jpg"],
 ["Quarter Ló","64.jpg"],
 ["Varázslatos lovak Umbra","65.jpg"],
 ["Varázslatos lovak Ayla","66.jpg"],
 ["Varázslatos lovak Vega","67.jpg"],
 ["Irish cob","68.jpg"],
 ["Varázslatos lovak Fawncy","69.jpg"],
 ["Chincoteague","71.jpg"],
 ["Varázslatos lovak Woodear","72.jpg"],
 ["Varázslatos lovak Tökmag","73.jpg"],
 ["Andalúz","75.jpg"],
 ["Varázslatos lovak Barkhart","76.jpg"],
 ["Akhal-Teke","77.jpg"],
 ["Clydesdale","78.jpg"],
 ["Jorvik Melegvérű","79.jpg"],
 ["Varázslatos lovak Brinicle","80.jpg"],
 ["Varázslatos lovak Zóni","81.jpg"],
 ["Fjord lovak","82.jpg"],
 ["Trakehneni","83.jpg"],
 ["Jorvik kezdő póni","84.jpg"],
 ["Luzitán","85.jpg"],
 ["Északsvéd ló","86.jpg"],
]